### ISSUE TITLE
Error exakat.ini

### ISSUE THREAD

**Issue by maitrepylos** [vonglasow/exakat-vagrant#10]
Hi,
`Fatal error: Uncaught Exakat\Exceptions\NoPhpBinary: PHP binary for version 5.4 is not valid : "/usr/local/bin/php54". Please, check config/exkat.ini in phar:///home/vagrant/exakat.phar/library/Exakat/Phpexec.php:119
Stack trace:
#0 phar:///home/vagrant/exakat.phar/library/Exakat/Config.php(292): Exakat\Phpexec->__construct('5.4')
#1 phar:///home/vagrant/exakat.phar/library/Exakat/Config.php(204): Exakat\Config->readProjectConfig('sculpin')
#2 phar:///home/vagrant/exakat.phar/library/Exakat/Config.php(230): Exakat\Config->__construct(Array)
#3 phar:///home/vagrant/exakat.phar/library/Autoload.php(64): Exakat\Config::factory(Array)
#4 /home/vagrant/exakat.phar(7): require_once('phar:///home/va...')
#5 {main}
  thrown in phar:///home/vagrant/exakat.phar/library/Exakat/Phpexec.php on line 119
vagrant@vagrant-exakat:~$ /usr/local/bin/php54 -v
-bash: /usr/local/bin/php54: No such file or directory

`

Solution, to comment

`php70        = 
`
And
`
php54        = /usr/local/bin/php54
`

@+

**Comment by dseguy** [comment]
So, I'll have to make it clearer in the docs : 
PHP 7.0 is needed to run Exakat (It should run with lower version too, but apparently it slipped through the net). 
Then, config/exakat.ini may have various version of PHP to be used for the actual analysis. 

So, ATM, run it with PHP 7.0, but configure the project (project/*/config.ini) with the version you want.

**Comment by maitrepylos** [comment]
No it is rather clear, it is just that in Exakat/config.ini, it is possible to use different version of PHP. the version 5.4 is declared, but not initialized in Vagrant. Thus it generates an error.
/usr/local/php Is configured well for PHP 7.

Sorry for my English.

**Comment by vonglasow** [comment]
fix in the last version used
