### ISSUE TITLE
How to use it

### ISSUE THREAD

**Issue by Mte90** [vonglasow/exakat-vagrant#19]
It is not clear from the readme how to symlink a folder to this machine and exekat with a specific config on it.
I want to avoid to enter on SSH and do a git clone of the files that I have already locally.

**Comment by dseguy** [comment]
http://exakat.readthedocs.io/en/latest/FAQ.html#can-i-run-exakat-on-local-code

Does that help ?

**Comment by Mte90** [comment]
I know how to run exakat the question is that exakat is inside the VM.
So how I can execute this command to parse a folder that is shared between the host and the VM?
This vagrant machine can do that?

**Comment by vonglasow** [comment]
Hello, 

Currently no, but it could be after some modifications.
The main goal of this vagrant is to install exakat and you can use it after easily, so to do what you need.

The vagrant during the provisioning must create a project first and mount your folder on the VM in right place. Then you can launch the analyze.

You will need to connect on this vagrant to launch the analyse or to get the report.

If you want a runner to do it without installation and no ssh connection you must look at https://github.com/exakat/exakat-docker

**Comment by Mte90** [comment]
For me is not a problem to use vagrant (I prefer to docker) but usually on vagrant there is a way to specify what folder is shared with the guest machine and I cannot find this stuff in the readme.
It is not a problem to enter vagrant to execute a command (I can do a script that use `vagrant ssh` for that).

I am trying to understand if this vagrant support a shared folder right now or I have to experiment to add it.

**Comment by vonglasow** [comment]
You can add an instruction to mount your folder on the vagrant then using exakat to parse it. 

You need to add it but it’s possible.

PR are welcomed :)

**Comment by Mte90** [comment]
Right now for me is not clear how to update exakat, `vagrant provision` didn't update the binary exakat I had to do that manually.

**Comment by vonglasow** [comment]
It's not yet implemented, I have created an issue about that (vonglasow/exakat-vagrant#30)

**Comment by Mte90** [comment]
Ok so this one can be closed.
