### ISSUE TITLE
Ansible failed to complete successfully. Any error output should be visible above. Please fix these errors and try again.

### ISSUE THREAD

**Issue by maitrepylos** [vonglasow/exakat-vagrant#8]
Salut,
J'ai voulu monter une exaket-vagrant, mais j'ai l'erreur suivante : 

`fatal: [default]: FAILED! => {"changed": false, "cmd": "apt-key adv --keyserver keyserver.ubuntu.com --recv EEA14886", "failed": true, "invocation": {"module_args": {"data": null, "file": null, "id": "EEA14886", "key": null, "keyring": null, "keyserver": "keyserver.ubuntu.com", "state": "present", "url": null, "validate_certs": true}, "module_name": "apt_key"}, "msg": "gpg: requesting key EEA14886 from hkp server keyserver.ubuntu.com\ngpg: no valid OpenPGP data found.\ngpg: Total number processed: 0", "rc": 2, "stderr": "gpg: requesting key EEA14886 from hkp server keyserver.ubuntu.com\ngpg: no valid OpenPGP data found.\ngpg: Total number processed: 0\n", "stdout": "Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.eLY6kFFCNf --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-security-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-stable.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-squeeze-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-squeeze-stable.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-wheezy-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-wheezy-stable.gpg --keyserver keyserver.ubuntu.com --recv EEA14886\n?: keyserver.ubuntu.com: Connection refused\ngpgkeys: HTTP fetch error 7: couldn't connect: Connection refused\n", "stdout_lines": ["Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.eLY6kFFCNf --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-security-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-stable.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-squeeze-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-squeeze-stable.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-wheezy-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-wheezy-stable.gpg --keyserver keyserver.ubuntu.com --recv EEA14886", "?: keyserver.ubuntu.com: Connection refused", "gpgkeys: HTTP fetch error 7: couldn't connect: Connection refused"]}

---

< PLAY RECAP >

---

```
    \   ^__^
     \  (oo)\_______
        (__)\       )\/\
            ||----w |
            ||     ||
```

default                    : ok=25   changed=22   unreachable=0    failed=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
`
Auriez-vous une piste ?

Merci.

**Comment by vonglasow** [comment]
@maitrepylos Étrange je n'ai pas eu l'erreur. Dans ce cas c'est l'accès au serveur distant qui n'a pas l'air d'avoir fonctionné. Normalement, tu peux essayer de relancer le provisionnement ça devrait fonctionner.

`vagrant up --provision`si la vm n'est pas déjà lancée
`vagrant provision` si la vm est déjà lancée.

English version to share it.

Apparently it looks an error from keyserver to download key you can try to provision the virtual machine again

try
`vagrant up --provision` if the virtual machine is stopped
`vagrant provision` if the virtual machine is already launched.

**Comment by maitrepylos** [comment]
Nop, j'ai fais pleins de tentative et cela ne fonctionne pas, toujours la même erreur, je vais tenter sur une autre machine pour voir.

**Comment by vonglasow** [comment]
ok strange, their should be available. Let me know the version of ansible you use and on which OS you try.

**Comment by maitrepylos** [comment]
Hello, thank you for helping me :)
gg@Portable-GG ~ $ ansible --version
ansible 2.0.0.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

gg@Portable-GG ~ $ cat /etc/os-release 
NAME="Linux Mint"
VERSION="18 (Sarah)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 18"
VERSION_ID="18"
HOME_URL="http://www.linuxmint.com/"
SUPPORT_URL="http://forums.linuxmint.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/linuxmint/"
UBUNTU_CODENAME=xenial

**Comment by vonglasow** [comment]
try latest version of sensible I use 2.1.0.0. I cannot reproduce bug for now. I will see if I can tomorrow.

**Comment by maitrepylos** [comment]
Hi, new ansible : 

gg@Portable-GG ~/Sites/exakat-vagrant $ ansible --version
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

error : 

fatal: [default]: FAILED! => {"changed": true, "cmd": "cd /home/vagrant/neo4j; ./bin/neo4j restart", "delta": "0:00:00.248206", "end": "2016-10-30 18:02:02.266278", "failed": true, "invocation": {"module_args": {"_raw_params": "cd /home/vagrant/neo4j; ./bin/neo4j restart", "_uses_shell": true, "chdir": null, "creates": null, "executable": null, "removes": null, "warn": true}, "module_name": "command"}, "rc": 2, "start": "2016-10-30 18:02:02.018072", "stderr": "", "stdout": "ERROR: Neo4j Server not running\nAnother server-process is running with [3000], cannot start a new one. Exiting.", "stdout_lines": ["ERROR: Neo4j Server not running", "Another server-process is running with [3000], cannot start a new one. Exiting."], "warnings": []}

---

< NO MORE HOSTS LEFT >

---

```
    \   ^__^
     \  (oo)\_______
        (__)\       )\/\
            ||----w |
            ||     ||

to retry, use: --limit @.ansible/exakat.retry
```

---

< PLAY RECAP >

---

```
    \   ^__^
     \  (oo)\_______
        (__)\       )\/\
            ||----w |
            ||     ||
```

default                    : ok=44   changed=22   unreachable=0    failed=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

**Comment by vonglasow** [comment]
Yep it looks better. I have made a fix regarding this kind of error, could you update your local repository and run `vagrant destroy && vagrant up`

**Comment by maitrepylos** [comment]
Ok Nice.

Par contre je remarque un drôle de truc et je te le fais en français :)
J'ai réussi à lancer le vagrant en téléchargeant le .zip et cela à fonctionné, par contre je ne comprenais pas pourquoi, tu me disais que c'étais bon et que je n'arrivais pas à lancer le vagrant avec la même erreur.

Du coup j'ai refait un git clone du projet et dans mon dépôt je n'ai pas les fichiers modifier.

Voici un exemple : 
`- name: test exakat-PHP
  lineinfile: dest=/home/vagrant/config/config.ini regexp="php          = "= line="php          = /usr/local/bin/php70"
  tags:
    - exakat
- name: test exakat-PHP 7.1
  lineinfile: dest=/home/vagrant/config/config.ini regexp=";php71        = /path/to/php71"= line="php71        = /usr/local/bin/php71"
  tags:
  - exakat
- name: test exakat-PHP 7.0
  lineinfile: dest=/home/vagrant/config/config.ini regexp=";php70        = /path/to/php70"= line="php70        = /usr/local/bin/php70"
  tags:
  - exakat
- name: test exakat-PHP 5.6
  lineinfile: dest=/home/vagrant/config/config.ini regexp=";php56        = /path/to/php56"= line="php56        = /usr/local/bin/php56"
  tags:
  - exakat
- name: test exakat-PHP 5.5
  lineinfile: dest=/home/vagrant/config/config.ini regexp=";php55        = /path/to/php55"= line="php55        = /usr/local/bin/php55"
  tags:
  - exakat
- name: test exakat-PHP 5.6
  lineinfile: dest=/home/vagrant/config/config.ini regexp=";php54        = /path/to/php56"= line="php54        = /usr/local/bin/php54"
  tags:
  - exakat
    `
    On voit bien que je continue à avoir un config.ini et non pas un exakat.ini comme tu l'as modifié.
    Cela me semble étrange.

Mais bon j'ai une machine pour tester Exakat, un grand merci à toi. :)

**Comment by vonglasow** [comment]
should be done also.
